FROM python:3.11-slim-bookworm
RUN set -eux; \
    apt-get update && apt-get install -y --no-install-recommends build-essential gcc g++; \
    rm -rf /var/lib/apt/lists/*
COPY ml/requirements.txt /tmp/requirements.txt
RUN python -m pip install --upgrade pip setuptools wheel && \
    pip install --no-cache-dir -r /tmp/requirements.txt
WORKDIR /workspace
