apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-runner
  labels:
    app: gh-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gh-runner
  template:
    metadata:
      labels:
        app: gh-runner
    spec:
      serviceAccountName: gh-runner-sa
      # GHCR 프라이빗 이미지가 필요하면 비밀키를 붙이세요(없으면 삭제해도 됨)
      imagePullSecrets:
      - name: ghcr-pull
      containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        env:
        - name: RUNNER_REPO_URL
          value: "https://github.com/nacgyun/mlopsgit"
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: gh-runner-secret
              key: token
        - name: RUNNER_LABELS
          value: "self-hosted,linux,x64,mlops,k8s"
        command: ["/bin/bash","-lc"]
        args:
        - |
          set -euo pipefail
          cd /home/runner
          ./config.sh \
            --url "$RUNNER_REPO_URL" \
            --token "$RUNNER_TOKEN" \
            --name "$HOSTNAME" \
            --labels "$RUNNER_LABELS" \
            --unattended \
            --ephemeral \
            --work _work
          exec ./run.sh

