apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gh-runner-deploy-admin
  namespace: mlops
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale", "replicasets"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments/status"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gh-runner-deploy-admin-binding
  namespace: mlops
subjects:
  - kind: ServiceAccount
    name: default        # gh-runner 파드가 쓰는 serviceAccountName이 default면 그대로 두고
    namespace: mlops
roleRef:
  kind: Role
  name: gh-runner-deploy-admin
  apiGroup: rbac.authorization.k8s.io

