apiVersion: batch/v1
kind: Job
metadata:
  name: mlflow-train-job
  namespace: mlops
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      serviceAccountName: gh-runner-sa
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-pull
      containers:
      - name: train
        image: ghcr.io/nacgyun/mlflow-train:latest   # 워크플로우에서 빌드한 이미지
        imagePullPolicy: Always
        command: ["python"]
        args: ["-u", "/app/train.py"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: MLFLOW_TRACKING_URI
          value: http://mlflow.mlops.svc.cluster.local:5000
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio.mlops.svc.cluster.local:9000
        - name: AWS_S3_FORCE_PATH_STYLE
          value: "true"
        - name: AWS_ACCESS_KEY_ID
          valueFrom: { secretKeyRef: { name: minio-root, key: root-user } }
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom: { secretKeyRef: { name: minio-root, key: root-password } }
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        - name: N_ESTIMATORS
          value: "100"
        - name: MAX_DEPTH
          value: "5"
        volumeMounts:
        - name: train-src
          mountPath: /app
      volumes:
      - name: train-src
        configMap:
          name: train-script

