apiVersion: batch/v1
kind: Job
metadata:
  name: mlflow-train-job
  namespace: mlops
spec:
  backoffLimit: 0
  template:
    metadata:
      labels: { app: mlflow-train }
    spec:
      restartPolicy: Never
      serviceAccountName: gh-runner-sa
      containers:
        - name: train
          image: python:3.10-slim
          command: ["bash","-lc"]
          args:
            - |
              set -euo pipefail
              pip install --no-cache-dir mlflow scikit-learn
              python /app/train.py
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow.mlops.svc.cluster.local:5000"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://minio.mlops.svc.cluster.local:9000"
            - name: AWS_ACCESS_KEY_ID
              valueFrom: { secretKeyRef: { name: minio-root, key: root-user } }
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom: { secretKeyRef: { name: minio-root, key: root-password } }
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - { name: N_ESTIMATORS, value: "100" }
            - { name: MAX_DEPTH,    value: "5" }
          volumeMounts:
            - { name: train-src, mountPath: /app }
      volumes:
        - name: train-src
          configMap: { name: train-script }
