name: build-and-push-ghcr
on: [push]

permissions:
  contents: read
  packages: write    # GHCR 푸시하려면 필요

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ml/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mlflow-train:latest
          platforms: linux/amd64

