name: CI/CD

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Apply Kubernetes manifests
        run: |
          set -eux
          kubectl -n mlops apply -f k8s/   # ← 여기 manifests 있는 폴더 지정
          kubectl -n mlops rollout status deploy/light-serve --timeout=300s

