name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    env:
      NAMESPACE: mlops
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # curl 없이 동작하는 JS 액션 (Node 기반) – PATH 자동 설정
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Diagnostics (whoami/env/kubectl)
        run: |
          set -x
          whoami
          uname -a
          which kubectl || true
          kubectl version --client
          echo "KUBECONFIG=${KUBECONFIG:-<none>}"
          ls -l /var/run/secrets/kubernetes.io/serviceaccount || true

      - name: Configure in-cluster kubeconfig
        run: |
          set -euo pipefail
          API="https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}"
          SA_TOKEN="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
          CA="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          kubectl config set-cluster in-cluster --server="$API" --certificate-authority="$CA" --embed-certs=true
          kubectl config set-credentials sa --token="$SA_TOKEN"
          kubectl config set-context in-cluster --cluster=in-cluster --user=sa --namespace="$NAMESPACE"
          kubectl config use-context in-cluster
          kubectl get ns "$NAMESPACE"

      - name: Apply manifests
        run: |
          set -euo pipefail
          for d in k8s manifests kubernetes; do
            if [ -d "$d" ]; then MANIFEST_DIR="$d"; break; fi
          done
          if [ -z "${MANIFEST_DIR:-}" ]; then
            echo "::error::No manifest directory found (expected: k8s/ or manifests/ or kubernetes/)"
            exit 1
          fi
          echo "Applying from $MANIFEST_DIR"
          kubectl -n "$NAMESPACE" apply -R -f "$MANIFEST_DIR"
          kubectl -n "$NAMESPACE" get all -o wide

