name: SelfHosted KubeCheck
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: [self-hosted, linux, x64, mlops, k8s]
    steps:
      - uses: actions/checkout@v4

      - name: Configure kubectl (persist KUBECONFIG)
        shell: bash
        run: |
          set -euo pipefail
          TOKEN_PATH="/var/run/secrets/kubernetes.io/serviceaccount/token"
          CA_PATH="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          KCFG="${RUNNER_TEMP}/kubeconfig"

          # 환경변수 영향 제거
          unset KUBERNETES_SERVICE_HOST KUBERNETES_SERVICE_PORT

          # kubeconfig를 직접 생성(서비스 DNS로 고정)
          kubectl config set-cluster in-cluster \
            --server="https://kubernetes.default.svc:443" \
            --certificate-authority="${CA_PATH}" \
            --embed-certs=true \
            --kubeconfig="${KCFG}"

          kubectl config set-credentials sa \
            --token="$(cat ${TOKEN_PATH})" \
            --kubeconfig="${KCFG}"

          kubectl config set-context in-cluster \
            --cluster=in-cluster --user=sa \
            --kubeconfig="${KCFG}"

          kubectl config use-context in-cluster --kubeconfig="${KCFG}"

          # 잡 전체에 적용
          echo "KUBECONFIG=${KCFG}" >> "$GITHUB_ENV"

          echo "== kubeconfig server =="
          kubectl --kubeconfig="${KCFG}" config view --minify --raw | sed -n 's/ *server: *//p'

      - name: Sanity check
        shell: bash
        run: |
          set -euo pipefail
          # 서버 주소 확인
          kubectl config view --minify --raw | sed -n 's/ *server: *//p'
          # 빠른 타임아웃으로 확인
          kubectl version --short --request-timeout=5s
          kubectl get ns --request-timeout=5s

      - name: Say hello
        run: |
          echo "Runner: $RUNNER_NAME"
          echo "Kube is reachable ✅"
